### ISSUE TITLE
`sample-mvn` throws a casting exception.

### ISSUE THREAD

**Issue by dkushner** [incanter/incanter#312]
Currently trying to sample some values from a multivariate normal distribution and receiving the following exception, even when the function is used exactly as documented:

```
java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to java.lang.Number
        at clojure.lang.RT.doubleCast(RT.java:1298)
        at mikera.vectorz.matrix_api$vectorz_coerce_STAR_.invoke(matrix_api.clj:218)
        at mikera.vectorz.matrix_api$eval11623$fn__11624.invoke(matrix_api.clj:1277)
        at clojure.core.matrix.protocols$eval2129$fn__2143$G__2118__2150.invoke(protocols.clj:494)
        at clojure.core.matrix$mmul.invoke(matrix.clj:1388)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:630)
        at incanter.core$mmult.doInvoke(core.clj:751)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at incanter.stats$sample_mvn.doInvoke(stats.clj:346)
        at clojure.lang.RestFn.invoke(RestFn.java:486)
        at quant.core$eval19598.invoke(form-init2687520589156269763.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6745)
        at clojure.core$eval.invoke(core.clj:3081)
        at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
        at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
        at clojure.main$repl$fn__7108.invoke(main.clj:258)
        at clojure.main$repl.doInvoke(main.clj:258)
        at clojure.lang.RestFn.invoke(RestFn.java:1523)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__16997.invoke(interruptible_eval.clj:58)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
        at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__17039$fn__17042.invoke(interruptible_eval.clj:191)
        at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__17034.invoke(interruptible_eval.clj:159)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

Function that causes this exact exception is as follows:

```
(sample-mvn 1000 :mean [7 5] :sigma (matrix [[2 1.5] [1.5 3]]))
```

Although this same exception is thrown even if only the required parameters are specified.

**Comment by mikera** [comment]
Yup verified this is an issue... sample-mvn is doing something odd

**Comment by mikera** [comment]
Is sigma supposed to be a correlation matrix or a covariance matrix? It isn't clear to me from the docs....

**Comment by dkushner** [comment]
@mikera, I was also unsure form the documentation but in general multivariate normal distributions are defined by a mean vector and covariance matrix, yeah. Not sure if the relevant dimensionality checks are in place, but the mean vector is expected to be of dimensionality _k_ and the covariance matrix, _k x k_.
